services:
  git-server:
    build:
      context: ./git
      dockerfile: Dockerfile
    container_name: git-server-container1
    ports:
      - "8000:8000"
    networks:
      - shared-network

  code-editor:
    build:
      context: ./editor
      dockerfile: Dockerfile
    container_name: code-editor-container1
    ports:
      - "3000:3000"
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge
